// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"easygo-agent/internal/controller"
	"easygo-agent/internal/repository/chatcache"
	"easygo-agent/internal/service/chat"
	"easygo-agent/internal/service/user"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitControllers(db *gorm.DB, cacheCfg chatcache.Config) *controller.AllControllers {
	userService := user.NewUserService(db)
	userController := controller.NewUserController(userService)
	chatSessionService := chat.NewChatSessionService(db)
	chatSessionController := controller.NewChatSessionController(chatSessionService)
	chatCacheRepo := chatcache.NewChatCacheRepo(cacheCfg)
	chatMessageService := chat.NewChatMessageService(db, chatCacheRepo)
	chatMessageController := controller.NewChatMessageController(chatMessageService)
	agentChatService := chat.NewAgentChatService(db, chatCacheRepo, chatMessageService)
	allControllers := &controller.AllControllers{
		User:      userController,
		Session:   chatSessionController,
		Message:   chatMessageController,
		AgentChat: agentChatService,
	}
	return allControllers
}
