// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"easygo-agent/internal/agent"
	"easygo-agent/internal/controller"
	"easygo-agent/internal/credential"
	"easygo-agent/internal/platform/auth"
	"easygo-agent/internal/service/account"
	"easygo-agent/internal/service/chat"
	"easygo-agent/internal/service/providerconfig"
	"easygo-agent/internal/service/user"
	"easygo-agent/internal/skill/store"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitControllers(db *gorm.DB, cipher *credential.Cipher, issuer *auth.Issuer, runtime *agent.RuntimeFactory, skills *store.Store) *controller.AllControllers {
	userService := user.NewUserService(db)
	userController := controller.NewUserController(userService)
	service := account.New(userService, issuer)
	authController := controller.NewAuthController(service)
	providerconfigService := providerconfig.New(db, cipher, runtime)
	providerController := controller.NewProviderController(providerconfigService)
	runService := chat.NewRunService(db, runtime, providerconfigService)
	executionService := chat.NewExecutionService(runService)
	chatController := controller.NewChatController(runService, executionService)
	skillController := controller.NewSkillController(skills)
	allControllers := &controller.AllControllers{
		User:     userController,
		Auth:     authController,
		Provider: providerController,
		Chat:     chatController,
		Skill:    skillController,
	}
	return allControllers
}
